# Generated by Django 2.1.7 on 2019-03-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=70)),
                ('Stu_roll_no', models.IntegerField()),
                ('stu_section', models.CharField(max_length=5)),
                ('Stu_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
