# Generated by Django 2.1.7 on 2019-03-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('value', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'task',
            },
        ),
        migrations.AlterModelOptions(
            name='student_form',
            options={'verbose_name_plural': 'Student_form'},
        ),
    ]
